Mobile menu
Jolak5/Portfolio pull request #14
Opened 2022-12-20 07:48 UTC by Jolak5

In this PR, I

1. refactored my HTML code
2. used CSS to hide some elements
3. used javascript to create the responsive hamburger

2022-12-20 09:14 UTC, Munsa1 requested changes
Hi  @Jolak5, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the correct linter configurations, this project uses Javascript. Kindly follow this [link](https://github.com/microverseinc/linters-config/tree/master/html-css-js)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-20 13:43 UTC, GzimAsani requested changes
### Hello  @Jolak5                             :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with your project, hamburger button works as expected :+1: 

 ## Required Changes 
- [ ] Check the comments below :arrow_double_down: 



 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-20 13:43 UTC, GzimAsani commented on index.html
> +          </div>
- [ ] When the hamburger is clicked it looks different than on design, kindly handle this:
Yours:
![image](https://user-images.githubusercontent.com/62705947/208680137-4be817a8-fb2b-455d-ac48-071419c4ebd6.png)
Desing:
![image](https://user-images.githubusercontent.com/62705947/208680049-ce96f6d3-4254-4e37-a10c-bf9c16ea1194.png)

2022-12-20 13:43 UTC, GzimAsani commented on index.html
> +          </div>
- [ ] Welcome should  be present only on mobile
![image](https://user-images.githubusercontent.com/62705947/208680347-d75a4a37-6204-4e5e-a74e-f6233f471bba.png)

2022-12-20 13:43 UTC, GzimAsani commented on index.html
> +          </div>
- [ ] After I open the hamburger menu and click on any of the options, they send me to the correct part of the page, but after that, I cannot move on your app anymore, kindly check that

2022-12-20 13:43 UTC, GzimAsani commented on index.html
> +          </div>
- [ ] According to the design the welcome and hamburger button should be on the same line
![image](https://user-images.githubusercontent.com/62705947/208680812-8ea0eca0-1cc1-4bd3-bd0e-a3aac6f4bc84.png)

2022-12-21 11:17 UTC, Owusu-Desmond approved these changes
Hi @Jolak5 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-24 09:07 UTC, merged